### ISSUE TITLE
Mime type or extension not allowed

### ISSUE THREAD

**Issue by BlessingD** [farquet/QuizGenerator#1]
Hi,I tried uploading a latex file on the admin page  but the page keeps telling me that the mime type or extension of the file is not allowed, I have checked the allowed mime types and file extensions and my file complies with both of them.Any ideas what could be causing this?I even tried your files that are in the latex-samples folder but I still get the same error message when i try to upload.  thanks a lot in advance

![error](https://user-images.githubusercontent.com/35054400/55157318-c37f7380-5164-11e9-84ea-e6564929de8d.PNG)

**Comment by farquet** [comment]
This was not really a bug ?

**Comment by BlessingD** [comment]
Yes it wasn’t, my bad. Only managed to sort it out now. It was the file I was trying to upload. However, may you kindly explain to me how you know which answer is the correct one in the tex file?Thanks a lot man!! this such a great project

**Comment by farquet** [comment]
I see.
The correct answer is stated in bracket after the `\question` tag.
See this example : 
```
  \question[2]{Ciphertext stealing ... }
 {results in the expansion  of the plaintext.}
 {prevents the expansion of the ciphertext.}
 {requires an additional secret key.}
 {steals ciphertext which results in lack of encrypted data.}
```
It means that the correct answer is the number 2, so `prevents the expansion of the ciphertext.`. Note that it starts counting at 1.

I notice that this is indeed not stated in the documentation.
If you play around with this project or modify it, please do not hesitate to submit pull requests to add features or documentation.

**Comment by BlessingD** [comment]
thanks a lot man! I will, and then is there a quick way of converting lets say questions in a word document to a latex document with the exact format that can be uploaded on this system,I found www.grindeq.com but I have to edit the latex file again after conversion to get the desired format for uploading.(as in the syntax and all that)

**Comment by BlessingD** [comment]
Hi Francois,This is not an issue,just a quick question,do you think I can
be able to upload latex files that have image files referenced in them?I am
using it for Maths and Science quizzes and most of the questions have
diagrams in them,I have made PNG files of the diagrams.Any pointers would
be great.Thanks

**Comment by farquet** [comment]
Hi,

I don’t think the current project would support this out of the box. If we wanted to do it nicely, we could add references to external dependencies (i.e. images) and handle those specially at upload time. But that would require some work.
A simpler but hackier way would be to encode the images directly in the latex file and add a small conversion rule to display them properly in the HTML output.

Either way, that would require more or less work. If you tackle this, please open a PR. Contributions are always appreciated.

**Comment by BlessingD** [comment]
Alright, all this advise is greatly appreciated.Let me try encoding the images directly into the latex files and see how it goes. I will definitely make some Pull requests if I get this right.Thanks once again for your time mate!

**Comment by farquet** [comment]
Doesn’t look that complicated.

Your Latex files need to embed the images as described here : https://tex.stackexchange.com/questions/208819/embedding-images-in-tex-file-as-base64-strings <https://tex.stackexchange.com/questions/208819/embedding-images-in-tex-file-as-base64-strings>

You need to modify the QuizGenerator to detect that pattern and extract the relevant bits.

Then simply embed the base64 content in the generated HTML like so : https://stackoverflow.com/questions/8499633/how-to-display-base64-images-in-html <https://stackoverflow.com/questions/8499633/how-to-display-base64-images-in-html>

HTH

**Comment by BlessingD** [comment]
Hi Farquet.Just something I picked up while working with the quiz generator system.I uploaded my quiz and it was working fine, but when I attempetd the quiz once, when I try and take it again, it doesnt display the questions at all and when I went to the admin page,this is whats displayed
![quizGenerator](https://user-images.githubusercontent.com/35054400/61207597-c5f6e080-a6f5-11e9-983f-61a6516ba94e.PNG)

what could be the cause. thanks in advance for your help.

**Comment by farquet** [comment]
Looks like it’s not able to parse the answers for some reason

**Comment by BlessingD** [comment]
On the error log,it gives this error : "PHP Notice:  unserialize(): Error at offset 0 of..." so im assuming the data is being corrupted somehow..
